/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GreatestHitsRouteImport } from './routes/GreatestHits'
import { Route as AttributionsRouteImport } from './routes/Attributions'
import { Route as AboutRouteImport } from './routes/About'
import { Route as IndexRouteImport } from './routes/index'

const GreatestHitsRoute = GreatestHitsRouteImport.update({
  id: '/GreatestHits',
  path: '/GreatestHits',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/Attributions',
  path: '/Attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Attributions': typeof AttributionsRoute
  '/GreatestHits': typeof GreatestHitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Attributions': typeof AttributionsRoute
  '/GreatestHits': typeof GreatestHitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Attributions': typeof AttributionsRoute
  '/GreatestHits': typeof GreatestHitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/About' | '/Attributions' | '/GreatestHits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About' | '/Attributions' | '/GreatestHits'
  id: '__root__' | '/' | '/About' | '/Attributions' | '/GreatestHits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttributionsRoute: typeof AttributionsRoute
  GreatestHitsRoute: typeof GreatestHitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/GreatestHits': {
      id: '/GreatestHits'
      path: '/GreatestHits'
      fullPath: '/GreatestHits'
      preLoaderRoute: typeof GreatestHitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Attributions': {
      id: '/Attributions'
      path: '/Attributions'
      fullPath: '/Attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttributionsRoute: AttributionsRoute,
  GreatestHitsRoute: GreatestHitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
